name = "my-app"
account_id = "f785052107c721eaade341bb8c675fe0"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2022-07-12"
workers_dev = true

KV_NAMESPACE_ID = "2c57616c0dd746769af400d7a709bfa0"

CLOUDFLARE_API_TOKEN = "Kr08Hc80Kf53Sxqob5VJK4UW4pwTkhHhqvdTCArU"

kv_namespaces = [
  { binding = "MY_KV", id = "2c57616c0dd746769af400d7a709bfa0" }
]